language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: KsDLR8notwpT9eMVd6uD6dHNR0drxBrNTV9ULuTzXeBPr57omoVDbliwpT1UYkECA8JkFO/vyIXAPyakF/512IhfjTHlQblVWBdrxwUH8VMCQtZpNAqtI4aWfd0TE7QcJn8bgU+fWe9xGIpVFL9bZLCjXoYrrXE0iYsiFfzqSKdmivoPyoUwxgml98PocfehVOZPBj2KPRY99zsoK2NJrsDTN+4o9NODMpXWeR3u9ZxWFlENxMFaAO+E/lbC3JVPDT2HIcz/eEN+C7ez02VZb0lwsNqkjqtPuW5oJFC2jiWSIGh0D1yq4YV7PDyZyyoML1b1qJc6aYnrz1MsMbmIzVAHjxNq5eHySNuiih+Ox9wbFuMw2kXDEWL9yR1haIwmGeZJ+E3MOiJWKeMPv7oRy/4BHU73G615m9AR88VjRNka//CIAvfecgU/YS9VTdHGdvsza23Vn8ekr3SkKlLGziyy+3fNcYYikCgVhOEwkvztsflJUHi9NVJ8muORgPOiXVrlOzj1XO3+dLVH8d2ZIdkS4UGFyPd7p2aj8wmNsbcrNcaqRdZZ8+PW11aJOgABIUFxbjdFNwMTYKLsKrbltGzJS6Va2mknsexLLPMhER9WFx+8bYN2+t7njlU2OYqQp6UlLJdBK+7ysMgw2VL1yf3Odq2pEElOEuhrZTOulSE=
  app: thomas-noteful-v3
  on:
    repo: thinkful-ei25/thomas-noteful-v3
