language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: KDw6LEVXDsjiUGxdHDsQ/WHLEwk/KYeCFBCYh3fuX3JRVkjvwpPCt/QrUyPugiLS41ZhbJM6mmPRBgyYdA+N3ZGu29ZBEnMJ6QTDt6cPzsQP2e4oUdfxZJcPsYNPe9S5hSGbbsi5MZicbbBolWsSyg12+EHQpTHOSpC1YxwNGuoS328rXrwR6vnk+rVnx8ehkytVHQ+fJzlQ8Krhoh3Gy0WoDUTar4SYTnORU6ltTOI/qQfhj4mSdmKpoJAEzYFqwTtRpvhhlDlMyi8ihG7Any+N1PlbPlNWplFsuXkPRVt6LXWgdrg74D9l0Sjmvg68/BlgNXmqzyjZm+/CV98Cfv0MyMeWeXpCihhMMrtQJrj7gSbggWHL2bo6+Uk6Pxds4G9bcBg8cZsEAtHnreE3A9wHn7e75iJ1Yh/q/60ik7OTPuHYa0wvStu6szOme3+Nru9Yok1rzChTkwUE3g4GFPzMwn/lna+9Vnu1TxrgTav2jBxwjWxMJiAQ+PSnNg6hoH2eeLY8T+lYoAwo8cAP/HYIk33vTTE1ZWWewSlHIQ5g9UUJzLiuLdBWioljM0uCjNlu3siWg2nRbwUqQlHIgLPKRfNmbUIFQBbuYEurJCeJSElwkxV8Nv3Fx0H5rSlJChEOTf6skP2fx0ZdPwA95zIo+0zfH8/3NKyaoPc7xC0=
  app: thomas-noteful-app-v3
  on:
    repo: thinkful-ei25/thomas-noteful-v3
